"""Configuration Pydantic models for case and model configs."""

from __future__ import annotations

from pydantic import BaseModel, Field


class GroundTruthFigure(BaseModel):
    metric: str
    value: str | None = None
    old_value: str | None = None
    new_value: str | None = None


class GroundTruthEvent(BaseModel):
    event_id: str
    event_date: str
    description: str
    event_type: str
    source_url: str | None = None
    key_figures: list[GroundTruthFigure] = Field(default_factory=list)


class CaseConfig(BaseModel):
    """Configuration for a single analysis case.

    Only 3 fields are required: company, strategy_theme, cutoff_date.
    Everything else is optional and will be auto-generated by the LLM
    if not provided.
    """

    # Required — the minimum input
    company: str
    strategy_theme: str
    cutoff_date: str

    # Optional — auto-generated if missing
    case_id: str | None = None
    regions: list[str] = Field(default_factory=list)
    peers: list[str] = Field(default_factory=list)

    # Optional — only for backtesting
    ground_truth_events: list[GroundTruthEvent] = Field(default_factory=list)
