"""Configuration Pydantic models for case and truth configs.

The case config is **agent-visible**: every field can flow into prompts.
The truth config is **evaluation-only**: read by the backtest path and
nowhere else. They are physically separated so that label-leakage paths
can be enforced at the loader boundary (L1.3, audit invariant).
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, Field, field_validator


# ── Truth-side models (eval-only, never loaded by agents) ──


class GroundTruthFigure(BaseModel):
    metric: str
    value: str | None = None
    old_value: str | None = None
    new_value: str | None = None


class GroundTruthEvent(BaseModel):
    event_id: str
    event_date: str
    description: str
    event_type: str
    source_url: str | None = None
    key_figures: list[GroundTruthFigure] = Field(default_factory=list)


class TruthConfig(BaseModel):
    """Evaluation-only ground truth for a case.

    Loaded ONLY by the backtest path (sfewa.agents.backtest) and the truth
    loader in main.py. Must never be imported or read by retrieval, extraction,
    analyst, adversarial, or synthesis code.

    The `sentinel` field carries a unique marker string used by the runtime
    leakage test to verify no truth content reaches agent-visible prompts.
    """

    case_id: str
    known_outcome: str | None = None
    validation_notes: str | None = None
    # ISO date when the outcome became public knowledge.
    # Used to compute "advance warning" intervals at evaluation time.
    outcome_disclosed_at: str | None = None
    sentinel: str | None = None
    ground_truth_events: list[GroundTruthEvent] = Field(default_factory=list)


# ── Case-side model (agent-visible) ──


class CaseConfig(BaseModel):
    """Agent-visible configuration for a single analysis case.

    Three fields are required: company, strategy_theme, cutoff_date.
    Everything else is optional and is auto-generated by the LLM if missing.

    The L1 audit fields (case_type, allowed_sources, doc_types, verifier_corpus,
    jurisdiction, ticker) describe the audit envelope of the run; they are
    safe to include in agent prompts.

    Truth content (known outcomes, ground truth events) is intentionally
    NOT a field on this model — it lives in TruthConfig in configs/truth/.
    """

    # Required — the minimum input
    company: str
    strategy_theme: str
    cutoff_date: str  # ISO YYYY-MM-DD

    @field_validator("cutoff_date", mode="before")
    @classmethod
    def _normalize_cutoff(cls, v: object) -> str:
        # YAML parses unquoted YYYY-MM-DD as datetime.date; normalize to ISO string
        # so downstream string-based date arithmetic keeps working.
        if isinstance(v, date):
            return v.isoformat()
        return v  # type: ignore[return-value]

    # Optional — auto-generated if missing
    case_id: str | None = None
    regions: list[str] = Field(default_factory=list)
    peers: list[str] = Field(default_factory=list)

    # ── L1 audit fields (added 2026-05-05) ──
    # case_type: drives loader/verifier behavior. Retrospective cases MUST
    # have a matching truth file; forward cases MUST NOT.
    case_type: Literal["retrospective", "forward"] = "retrospective"
    # jurisdiction: ISO-style code ("HK", "JP", "CN", "US"). Optional —
    # filing_discovery still falls back to name-pattern detection.
    jurisdiction: str | None = None
    # ticker: primary listing ticker. Required for HKEX; optional elsewhere.
    ticker: str | None = None
    # allowed_sources: source identifiers permitted for retrieval & verifier
    # (e.g. ["edinet", "cninfo", "hkexnews", "duckduckgo", "news"]).
    # Empty list = no restriction (default behavior preserves backward compat).
    allowed_sources: list[str] = Field(default_factory=list)
    # doc_types: filing document types permitted (e.g. ["annual_report",
    # "interim_report"]). Empty list = no restriction.
    doc_types: list[str] = Field(default_factory=list)
    # verifier_corpus: scope for Phase 2 adversarial verification search.
    # None = auto-derive from case_type (retrospective → allowed_sources_only,
    # forward → open_web). Loader applies the default.
    verifier_corpus: Literal["allowed_sources_only", "open_web"] | None = None


# ── Loader (the leakage-prevention boundary) ──


def _read_yaml(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f) or {}


def load_case(path: Path) -> CaseConfig:
    """Load a case YAML. Strips ground_truth_events if present (legacy migration)."""
    raw = _read_yaml(path)
    # Defense in depth: silently strip truth-shaped fields from the case config
    # so a misplaced ground_truth_events block in a case YAML cannot leak.
    # The loader is the single boundary; we fail soft and the static + sentinel
    # tests fail loud.
    raw.pop("ground_truth_events", None)
    raw.pop("known_outcome", None)
    return CaseConfig(**raw)


def load_truth(path: Path) -> TruthConfig:
    """Load a truth YAML. Caller is responsible for restricting access."""
    raw = _read_yaml(path)
    return TruthConfig(**raw)


def load_case_and_truth(
    case_path: Path,
    truth_dir: Path | None = None,
    case_id: str | None = None,
) -> tuple[CaseConfig, TruthConfig | None]:
    """Load a case and its matching truth file (if any), validating the relationship.

    Args:
        case_path: Path to the case YAML.
        truth_dir: Directory containing truth YAMLs. Defaults to
            configs/truth/ relative to the case file's parent.
        case_id: Override case_id used for truth file lookup. If None, uses
            CaseConfig.case_id (after loading) — caller may need to set this
            if the case YAML omits case_id.

    Returns:
        (CaseConfig, TruthConfig | None)

    Raises:
        FileNotFoundError: retrospective case with no matching truth file.
        ValueError: forward case with a truth file present (label leakage hazard).
        ValueError: case_id mismatch between case and truth files.
    """
    case = load_case(case_path)

    # Resolve truth directory. Default: sibling of case_path's parent.
    if truth_dir is None:
        truth_dir = case_path.parent.parent / "truth"

    lookup_id = case_id or case.case_id
    if lookup_id is None:
        # Without a case_id we can't locate the truth file. For retrospective
        # cases this is a configuration error; for forward cases it's fine.
        if case.case_type == "retrospective":
            raise ValueError(
                f"Retrospective case '{case_path}' has no case_id; "
                f"cannot locate truth file."
            )
        return case, None

    truth_path = truth_dir / f"{lookup_id}.yaml"
    truth_exists = truth_path.exists()

    if case.case_type == "forward" and truth_exists:
        raise ValueError(
            f"Forward case '{lookup_id}' must NOT have a truth file. "
            f"Found: {truth_path}. Forward cases are surveillance, not "
            f"retrospective validation — having known outcomes here is a "
            f"label-leakage hazard. Move it under configs/truth/ for a "
            f"retrospective case_id, or delete the file if the outcome "
            f"isn't known yet."
        )

    if case.case_type == "retrospective" and not truth_exists:
        raise FileNotFoundError(
            f"Retrospective case '{lookup_id}' requires a truth file at "
            f"{truth_path}. Either create it or set case_type: forward."
        )

    if not truth_exists:
        return case, None

    truth = load_truth(truth_path)
    if truth.case_id != lookup_id:
        raise ValueError(
            f"Truth file case_id mismatch: case='{lookup_id}' but truth file "
            f"at {truth_path} has case_id='{truth.case_id}'"
        )

    return case, truth


def apply_verifier_corpus_default(case: CaseConfig) -> CaseConfig:
    """Apply the L1.5 default for verifier_corpus when the case omits it.

    Default: retrospective → allowed_sources_only, forward → open_web.
    The loader path calls this so agents never see verifier_corpus=None.

    Cases that explicitly set verifier_corpus (including the iter-41
    baseline Honda/Toyota/BYD configs that pin "open_web") are unchanged.
    """
    if case.verifier_corpus is not None:
        return case
    default = (
        "allowed_sources_only" if case.case_type == "retrospective" else "open_web"
    )
    return case.model_copy(update={"verifier_corpus": default})
